### ISSUE TITLE
Andy's resume review

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#16]
https://docs.google.com/document/d/1LRFG83Di2oU9bXQNqA1NPwBeMzrqwndCo_drWKfW-hM/edit?usp=sharing

**Comment by btakeya** [comment]
* 전체적으로 좋습니다 👍

**Comment by GyuminLee** [comment]
제 생각도 전체적으로 깔끔하고 좋은 것 같습니다!

**Comment by rygh4775** [comment]
@btakeya 님의 resume를 참고하여 Activities를 추가하였습니다👍

**Comment by RoyMoon** [comment]
제가 구글에 입사하신분 이력서를 샘플로 받아봤는데 그분은 굵은 글씨로 자신의 기술/ 중요한 이력을 강조하셨는데 키워드를 강조하셔서 눈에 잘들어 왔습니다.  그런 것을 넣어보면 좋을꺼 같습니다.
**Java / Mysql, Hive, Elasticsearch and Kafka** 
그리고 Summary 가 있어서 경력이나 기술에 대해서 간단하게 기술하면 좋을꺼 같습니다.

**Comment by tgi01054** [comment]
이해하기 좋은 이력서 이네요. 

* 프로젝트 이름(?)
Long term preservation management system (LAEDOC)
Spending data visualization (Toy)
Business intelligence tool (Truenorth)
LAEDOC, Toy, Torutabi 등이 프로젝트 이름은 것 같네요.
문서 검토 하시는 분은 프로젝트 이름을 굳이 아실 필요까지는 없을 거 같네요.

* 성능 향상 강조 부분
저도 영어가 능숙하지 않지만 아래으로 수정해 보는 게 어떨까요?

```
Changed indexing process, which took more than 16 hours, to be done within 8 hours, using thread programming.
```
을 아래와 같이 이렇게 고쳐 보면 어떨까요?

```
Speed up 2X for indexing process with multi thread 
```

* H.I.S 
읽어보면 H.I.S.가 무엇인지 잠깐 생각하게 되네요.
Japanese Travel Agency 인거 같은데요... H.I.S 삭제하고 Japanese travel agency 라고 적는게 어떨까요?

* 편집 이슈 #1
Skills 아래에는 bullet(-, +, *) 으로 표시하는 것이 어떨까요? Working experience 에는 bullet으로 되어 있어서요.

* 편집 이슈 #2
Java, HTML, JS /  ElasticSearch, and AWS.
중간에 /가 특별한 의미가 있은 건가요? , 인거 같아요.

* 편집 이슈 #3 
중간에 MySQL을 Mysql 이라고 있네요.  사소하지만 MySQL 대소문자 명시하는 것으로 관련 지식의 깊이를 보여 줄 수 있습니다.

**Comment by rygh4775** [comment]
@RoyMoon 
- 키워드를 강조하는 방법도 좋은 것 같습니다. 어떤 키워드를 강조할지 고민해봐야겠네요.
- 저 같은 경우에는 Summary 대신 Skills로 이력서를 강조하고 있습니다. 
  > 소프트웨어 엔지니어는 Skills가 곧 Summary이지 않을까라는 생각도 가지고 있어요. 참고해서 조금 더 고민해보겠습니다 👍

**Comment by rygh4775** [comment]
@tgi01054 

- 프로젝트 이름(?)
생각해보니 프로젝트를 명시적으로 나타내지도 못하는 프로젝트 이름은 불필요하겠네요.
> 또 다시 생각해보니, 인터뷰에서 이야기할 때 프로젝트명을 가지고 질문을 하기도 하더라구요. 간단히 호칭하기 좋으니까요. 불필요한 줄바꿈을 발생시키지 않는 범위안에서는 넣는 것도 괜찮다는 생각이 드네요. 뭔가 연구용 프로젝트를 진행했다는 것 보다는 프로덕트를 만들었다는 느낌도 들구요..

- 성능 향상 강조 부분
원어민이 리뷰해줘서 수정한 내용이긴 한데, 내용이 다소 구절구절하긴 합니다.ㅎ
그렇지만 대략적으로 나타낸 시간을 없애면 볼륨을 강조하기 어려울 것 같기도 하네요.
참고해서 고민 해보겠습니다 👍

- H.I.S
H.I.S가 일본에선 네임벨류가 있는 기업이라 라쿠텐 지원시 넣었었던 건데 신경도 안쓰더군요. 뺐습니다ㅎ

- 편집 이슈 #1
좋은 생각입니다.

- 편집 이슈 #2
중간에 /은 사실 언어와 솔루션을 나누는 역활을 하는 표기인데요.
/의 좌측은 프로젝트 진행시 개발한 애플리케이션의 언어 위주로 작성을 하였고, 
/의 우측은 프로젝트 진행시 애플리케이션과 연동(?)한 솔루션 혹은 소프트웨어 위주로 작성을 했습니다.

- 편집 이슈 #3 
디테일하게 봐주셔서 감사합니다 :)

**Comment by qtsky89** [comment]
깔끔하고 잘 읽히는 이력서로 보입니다 :)
