### ISSUE TITLE
Benjamin's resume review

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#17]
https://drive.google.com/file/d/1ZiV8NIxddBdiStQsFJuc62edXJ-H31ua/view?usp=sharing

**Comment by btakeya** [comment]
* Objective 항목이 있는 것은 좋지만, 원하는 것을 문장형태로 쓰는 것이 통상적입니다. (자세한 내용은 검색 추천 ^^;)
* Experience 항목의 제목 줄에서 기간, Job title, 지역의 간격이 너무 좁아 구분이 되지 않습니다.
* Tech Skills가 Objective 다음으로 올라와서 내가 가진 스킬을 더 강조하면 좋을 것 같습니다.

**Comment by rygh4775** [comment]
윗글과 아랫글의 간격 사이가 너무 좁은 느낌입니다. 
수치화된 결과를 명시한 부분이 잘 보이는데요.
> 제 개인적으로는 수치들이 "훌륭한(?) 수치들이다"라는 걸 어필이 되면 더 좋을 것 같다라는 생각이 들었습니다.

**Comment by GyuminLee** [comment]
각 항목들의 날짜 / 장소의 위치들이 통일되어 있으면 좀 더 보기 좋을 것 같습니다.
(예를들어 education의 경우 날짜가 앞에 표시되어있고 프로젝트의 경우는 뒤에 표시되어 있는)
글씨 체도 바꾸면 더 좋을까요? (요건 저의 질문입니다. 다른 분들의 생각은 어떤지 여쭙고싶어서요 :))

**Comment by RoyMoon** [comment]
제가 구글에 입사하신분 이력서를 샘플로 받아봤는데 그분은 굵은 글씨로 자신의 기술/ 중요한 이력을 강조하셨는데 이런게 적용되면 좋을꺼 같습니다.

**Specialization for back-end system with Java, C, and C++** 
**REST**  and **Mongo DB** 
**Mongo DB, MySQL,** 
**Spring MVC, MyBatis, and Oracle** 
**monthly payment: 27 billion (KRW)** 
이런식으로 하면 키워드가 눈에 잘 들어 옵니다. 

카카오 같은 경우는 국내 최대 SNS 인데 이런 부분을 강조해서 간단하게 기술해놓으면 좋을꺼 같습니다. 이건 아이디어 입니다. 
ex) a Kakao talk is free free mobile instant messaging app. The app is also used by 93% of smartphone owners in South Korea

알려진 혼돈할 가능 성이 없는 약자의 자세한 설명은 불필요해 보입니다. 
REST(Representational state transfer)
SMTP(Simple Mail Transfer Protocol) servers 
SOAP(Simple Object Access protocol) APIs 

billing REST(Representational State Transfer) API withSpring MVC, MyBatis, and Oracle  <-- 위에서 설명한 약자를 다시 설명하는 것도 불필요 해보입니다.

**Comment by qtsky89** [comment]
주소를 아파트 호수 까지 명시할 필요는 없어 보입니다. (분당구나 성남시 정도만 되도 충분할 것 같습니다.)
TECHNICAL SKILLS 에서, 강조하고 싶은 기술들만 추려서 어느 정도 레벨 이다를 보여주는게 좋을 것 같습니다. (참고로 제가 구인담당자라면.. Editor 같은 건 궁금해 할 것 같지 않습니다)
