### ISSUE TITLE
Gyumin's resume review

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#18]
https://docs.google.com/document/d/1if9XoYD4xi8SzU2jEApT0fuqpOMEsTS_T3l2aAzoqlI/edit?usp=sharing

**Comment by btakeya** [comment]
* 해외 보안업계에서는 한국 군생활도 물리보안 경험으로 인정해주는 경우도 있다고는 들었는데, 소프트웨어 개발 경험이 아닌 이상은 이력으로 넣기는 어렵지 않나 생각합니다. (이건 전적으로 제 생각입니다)
* Tech Skills 항목이 가장 위로 오는 것이 좋을 것 같습니다. 보통 `내가 할 수 있는 것들`을 가장 강조하(=먼저 보여주)니까요.
* 제 경험상으론 구글 문서도구가 문서를 쓰긴 편해도 꾸미기 기능은 빈약해서 쉽진 않을 것 같습니다만, 전체적으로 문서에 여백이 많아보입니다. 너무 촘촘해도 보기 어렵겠지만, 불필요한 여백은 없애는 쪽이적은 문서에 많은 내용을 담기 좋지 않을까 생각해요.

**Comment by rygh4775** [comment]
저도 여백을 줄이는 것에 한표입니다. 그러면 2장 안에 내용을 담을 수 있을 것 같아요

**Comment by GyuminLee** [comment]
@btakeya 저도 군경력에 대해서는 많이 고민했는데 저의 빈약한.. 리주메의 칸을 채우기 위함과 어느정도의 코딩이 섞인 경험이라서 물어 봤을 경우 조금 살을 붙일 수 있을 부분이라 생각해서 추가했습니다! 가끔 인사담당자와 얘기할 때 신기해서 물어보는 경우도 많더라구요. 이 부분은 테크 회사에 지원할 때에는 빼야겠습니다. 
@rygh4775 여백 줄인 버젼으로 한 번 다시 써보겠습니다!

**Comment by GyuminLee** [comment]
다른 분들 쓴것 보니 경험 한 프로젝트에 대해서 좀 더 상세하게 써야 될 것 같습니다.
감사합니다 :)

**Comment by RoyMoon** [comment]
지원자 이력서를 볼때 먼저 보길 원하는건 해당 지원자의 경력 Summary 라고 합니다.. Summary를 만들어서 넣어 주시는게 좋아 보입니다.
프로젝트에 관한건 이미 언급하셨으니 넘어가고 사용하신 스킬/중요한 내용을 굵은 글씨로 강조하면 눈에 잘띌꺼 같습니다.

**Comment by tgi01054** [comment]
Top-down 으로 읽어서 이해 하기 좋은 이력서 입니다.

* Android 개발자 이시죠? 이 부분을 강조 하는 것이 어떨까요?

* 편집 이슈
Skills 에 English, German, Korean을 같은 bullet 에 두는 것은 어떨까요?
Java와 English가 같은 bullet 에 있으면 같은 부류라고 생각이 되어서요.

**Comment by qtsky89** [comment]
저도 Summary 가 제일 위에 있으면 좋을 것 같습니다. 어떤 스킬이 있으신지 한눈에 안들어 옵니다 :) 또.. projects 랑 work experience 가 간결한 건 좋은데.. 해당 프로젝트에서 어떤일을 했는지, 어떤 기술 스택을 가져다 썻는지 등등 좀더 내용이 있으면 좋을 것 같습니다.
