### ISSUE TITLE
Jason's resume review

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#19]
https://drive.google.com/file/d/1_mxBEi3BwiV4OpnWpahWWr-mUzB5-0kx/view?usp=sharing

**Comment by btakeya** [comment]
* 한국 자격증을 기록하는 것이 미국 회사에 얼마나 효과가 있을지 잘 모르겠습니다.
* 학부 졸업 아래 '졸업 논문 제목'임을 알리는 것이 좋을 듯 합니다. (특별한 설명이 없어도 그렇게 생각할 것 같긴 하지만 ^^;)
* 전반적으로 훌륭합니다 👍

**Comment by rygh4775** [comment]
> Improved 700% throughput performance... 

수 많은 이력서를 보는 사람이라면 이런 표현들이 눈에 뛸 것 같아요!

**Comment by GyuminLee** [comment]
저도 깔끔하고 좋다고 생각됩니다 👍

**Comment by RoyMoon** [comment]
작업하신 내용중 강조할꺼나 스킬에 대해서 굵은 글씨로 강조해서 눈에 띄게 해보세요.
**Developed search application, front proxy server, and design underlying NFS architecture** in Naver Cloud Search 

네이버 같은 회사는 최대 검색 엔진 회사인데 경력 기술할때 간단하게 언급하면 어떨까 합니다.

**Comment by tgi01054** [comment]
전체적으로 이해하기 좋은 이력서 입니다.

* Specialized in Search software 라고 있는데요.  
     Summary에 이렇게 기술하더라고 workking experience 더 상세할 설명이 필요할 것 같습니다. 
     Crawing, Indexing, 등 업무를 설명해야 왜 검색쪽 전문가 인지... 이해 할 수 있을 것 같습니다.

* Backend 개발자 분인지 frontend 개발자 분이지 강조해야 할 것 같습니다.

* Special skills 아래에 project experience  는 working  experience 으로 이동 하는 것이 어떨까요?

* 사소한 오타
이메일 주소 'Qtsky89@gmail.com' 앞에 Q는 대문자 인가요? 
만약 오타이면 인터뷰으로 부터 연락 못 받을 수 있을 것 같습니다.

**Comment by qtsky89** [comment]
@btakeya 님
 좋은 의견 감사합니다. 다만, 자격증의 경우 외국의 있는 한국 기업도 염두에 두고 있기 때문에, 도움이 아주 안되진 않을 것 같아 붙여 두었습니다. 예전에 IBM Korea 인턴 면접 볼 때, 정보처리기사 자격증 없는 친구가 제 옆자리 였는데, 남들 다 따는 자격증을 왜 안땃냐고 구박 받은 것을 들은 경험이 있어서요.

@rygh4775 님
 해당 오픈 소스의 경우 제가 작업할 당시만해도, 성능이 정말 안좋아 조금만 코드 수정만 해도 좋아 지는 상태 여서 높은 수치가 나온것 같습니다.

@GyuminLee 님
 감사합니다.

@RoyMoon 님
 굵은 글씨! 한번 활용해 보겠습니다.

@tgi01054 님
 검색도 여러 갈래가 있는데, 어떤것을 했는지, backend 인지 frontend 인지 등등 구체적으로 안쓴 것 같네요. 언급해주셔서 감사합니다.
 구글 메일의 경우, 대문자와 소문자를 다르게 취급하지 않습니다. 저도 qtsky89 으로 쓰고 싶지만, 이전에 gtsky89 로 실수해서 보내신 분이 있어서, 강조하게 위해 Q 를 사용 했습니다 ^^

**Comment by qtsky89** [comment]
> * 한국 자격증을 기록하는 것이 미국 회사에 얼마나 효과가 있을지 잘 모르겠습니다.
> * 학부 졸업 아래 '졸업 논문 제목'임을 알리는 것이 좋을 듯 합니다. (특별한 설명이 없어도 그렇게 생각할 것 같긴 하지만 ^^;)
> * 전반적으로 훌륭합니다 👍
