### ISSUE TITLE
Juhwan's resume review

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#20]
https://docs.google.com/document/d/1Z1ULWIr844CDJCb0GEsAXaw2r0cysdlV95DaM2cXJiY

**Comment by rygh4775** [comment]
저도 개인 프로젝트들이 몇개 있는데 Activities로 넣으면 좋겠네요.
개인 프로젝트들을 보통 private project라 하나요? personal project라고 하는 것 같기도 하고...

**Comment by btakeya** [comment]
@rygh4775 pet project라 부르기도 하고요. 영문 이력서를 처음 작성할 적에 private project 라는 표현을 들어서 그렇게 써왔는데, 지금 검색해보니 private project는 비공개 프로젝트 느낌이네요 -.-;

**Comment by GyuminLee** [comment]
들여쓰는 부분은 혹시 일부러 하신건가요?
예를들어 Computer Skill Profile에 framework와 other experiences 같은 경우 .. (experience의 경우 불가산 명사로 알 고있는데요.. 혹시 제가 틀린건지 확인 부탁드려요 ㅠㅠ)
또 Education에 MS / BS의 들여쓰기가 다른것에 이유가 있는지 궁금합니다.
내용이나 구조는 아주 좋은 것 같습니다!

**Comment by btakeya** [comment]
@GyuminLee 들여쓰기는 구분을 위해서 한 것입니다. (0단계 요약, 1단계 프로젝트 제목, 2단계 프로젝트 내용 요약)
그렇게 생각했을 때 Education의 항목도 0단계로 나오는게 맞겠네요 👍

그리고 말씀듣고 찾아보니 experience는 가산명사입니다 https://dic.daum.net/word/view.do?wordid=ekw000058678
근데 한편으로는 `직업이나 했던 일로부터 얻은 스킬 또는 경험`이란 의미로의 experience는 불가산명사라고도 하고요 -\_-; (knowledge or skill that you gain from doing a job or activity, https://ell.stackexchange.com/questions/34843/is-experience-countable-or-uncountable)
이부분은 그냥 non-native의 특권(?) 이라고 생각하고 틀리겠습니다 -_-;;

**Comment by RoyMoon** [comment]
지원자 이력서를 볼때 먼저 보길 원하는건 해당 지원자의 경력 Summary 라고 합니다.. Summary를 만들어서 넣어 주시는게 좋아 보입니다.
경력 사항중 사용하신 스킬/중요한 내용을 굵은 글씨로 강조하면 눈에 잘띌꺼 같습니다.
주소는 Korea 정도로 하는게 좋다고 다른분들이 제 이력서 보고 말씀해주시더라구요..

**Comment by btakeya** [comment]
@RoyMoon `Computer Skill Profile`이 summary 역할이라고 생각했는데, 말씀 듣고 보니 그런 느낌이 약했네요. 위치조정과 타이틀 수정(`Tech Skill Summary`)했습니다.
주소는 말씀처럼 외국인들은 상세주소 써봐야 알지도 못하고 관심도 없을테지만, 그렇다고 Korea만 쓰긴너무 허전한 것 같아서 -_-;

**Comment by tgi01054** [comment]
전체적으로 보기에 좋은 이력서 입니다.

* 전체적으로 분량을 1.5 페이지 정도으로 늘려 보는 것이 어떨까요?
  
* 수치 자료 
   할수 있다면 수치 자료를 넣으면 좋을 것 같습니다. 
Automated test framework for network appliance verification 이면 기존 대비 자동화 해서 테스트 시간이 단축이 얼마큼 되었다고 애기 가능하지 않을까요?

* 기술 용어
- common authorization service 라면 OAuth 등 인증 기법을 추가 하는 것이 어떨까요?
- Developed IPv6 packet generator to study behavioral characteristics of IPv6 packets 라면 개발 환경보다 어떤 알고리즘을 사용했는지가 더 관심을 받을 것 같습니다.

* 약어
1차 서류 검토하시는 분은 엔지니어가 아닌 경우가 많습니다. 
기술 용어 DPX 는 full name으로 적어 주시는 것이 좋을 것 같습니다.

* Object 추가
개발자 직군이 많습니다. SDE(Software Development Engineer), STE(Software Test Engineer), Solution engineer) 
어느 직군에 지원 했는지를 적는게 좋을 것 같습니다.

**Comment by btakeya** [comment]
@tgi01054 좋은 피드백 감사합니다 👍 
* 분량은 의도적으로 1장으로 맞췄습니다. 더 많은 이야기가 필요하다면 2장분량까지 넘어가는 것도 좋겠지만 아직은 아니라고 생각하고 있어요.
* 제가 했던 작업들을 어떻게 수치화 할 수 있는지 잘 감이 안잡히네요; 테스트 프레임워크는 없던 것을 새로 만든 것이고, 주로 관리 기능을 개발한거라 수치로 표현할 수 있는 지표를 어떻게 잡아야 할지 @.@; (최근에 진행중인 서비스는 물류 센터 현장에서 관리 효율을 올렸다는 성과가 있어서 이걸로 쓸 수 있을 것 같긴 합니다.)
* 기술용어
  * common authorization service가 자체적으로 구현한 마이크로서비스 간의 공통 사용자 인증이라 인증기법이 별도로 있진 않습니다. 오해를 줄이기위해 표현을 약간 수정했습니다. :)
  * IPv6 패킷 생성기는 네트워크 노드(실험에서는 tcpdump의 패킷 해석기능)가 IPv6 패킷 각 필드 값에 따라 패킷을 어떻게 인식하는지를 보기 위해 `IPv6 패킷의 특정 필드값을 임의로 변경하는 기능`을 구현한 것으로, 별도의 알고리즘을 사용하진 않습니다.
* 약어
  * DPX는 제품명입니다.
* Objective는 그 때 그 때 달라질 것 같아서 별도로 기록하지 않았습니다. (그래봐야 SDE겠지만 ^^;)

**Comment by tgi01054** [comment]
common authorization service 가 
표준 기술(예: OAuth)이 아니고 회사에서 자체적으로 구현하거라면
customized  authorization service
이런 표현을 쓰기로 합니다.

**Comment by qtsky89** [comment]
Tech Skills Profile 에서 각각의 스킬들의 숙련도가 어느 정도 되는지 적으면 좀더 좋을 것 같습니다. 구인 하는 사람 입장에서는, 이사람이 toy project 한번 해보고 이렇게 올린건지 아니면 숙련된 수준인지 가늠하기 힘들 것 같습니다.
