### ISSUE TITLE
Logan's resume review

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#21]
https://goo.gl/AKNZsv

**Comment by rygh4775** [comment]
Resume 보다는 CV인 것 같습니다만..
Resume라면 1페이지 혹은 많아도 2페이지 분량으로 정리를 하면 좋을 것 같습니다.

**Comment by btakeya** [comment]
* 개인정보란에 주소 표기: 시/군/구 정도까지만 써도 되지 않을까 생각합니다. (예: Bundang-gu, Seongnam-si, Gyeonggi-do, Republic of Korea) 미국에서 한국의 자세한 주소에 관심이 있을 것 같진 않고, 한국에 사는 사람이구나 정도 알리기 위한 목적으로.
* 앤디님 코멘트 관련,
  * Work Experience, Professional Experience를 합쳐서 정리할 수 있을 것 같습니다.
  * Technical Skills를 Professional Summary에 녹일 수 있을 것 같습니다.
* Education에 기간 추가
* Joining Month, Relieving Month -> 테이블의 제목 부분을 써야한다면 Start, End 정도로만 써도 될 것 같습니다. (사실 근본적으로 템플릿을 수정하는 것이 좋을 듯 합니다)
* 영문 날짜 표기는 March 2019 와 같은 형식으로 합니다. (사실 2019/03 같은 표기가 국제표준-ISO 8601이긴 한데, 미국 회사에 지원하려면 미국 양식에 맞춰야죠 ㅠㅠ)
* 이 부분은 듣긴 했지만 저도 와닿지 않는 것으로, 참고만 해주세요 :) Times Roman 같은 다소 딱딱한 폰트 보다는 격식있으면서도 부드러운 폰트를 쓰는쪽이 좋다고 하네요. 저는 Calibri를 썼습니다.

**Comment by GyuminLee** [comment]
저도 분량을 좀 줄였으면 좋다고 생각하지만 경력이 많으셔서 올바른건지는 잘 모르겠습니다.
개인적으로는 표 형식을 이용해서 프로젝트명 / 장소 / 날짜 이런식으로 틀을 만드시면 더 보기 좋을 것 같습니다.

**Comment by RoyMoon** [comment]
말씀해주신 내용 참고해서 조금 업데이트 했습니다.  학력은 나중에 다시 업데이트 하겠습니다.

**Comment by tgi01054** [comment]
진행한 프로젝트가 많으시네요.  중요한 프로젝트만 기입하는 것이 어떨까요? 
인터뷰어에게 더 임팩트 있게 보일 것 같습니다.

* 간략히 변경 가능 내용  #1
Summary 중에 
```
Experience in writing SQL queries, Stored Procedures for accessing and managing databases such as Oracle, MS-SQL, MySQL and PostGreSQL.
Experience in NoSQL (Redis).
Experience in issue tracking using JIRA, Redmine.
Configured Jenkins for automation of Build, Versioning, Source repository and Deployment.
```
은 skill sets 에  간단히 기입 할 수 있을 것 같습니다.
- DB: Oracle, MS-SQL, MySQL and PostGreSQL, Redis
- Issue tracking system: JIRA, Redmine
- CI(Continuous Integration) tool: Jenkis

* 간략히 변경 가능 내용  #2 
예를 들면 아래 Description 는 삭제 가능할 것 같습니다.
Senior architect 부분은 Role 에 들어 갈 것 같습니다. 
그리고 designing and developing core features는 Responsibilities 에 들어 갈 수 있습니다.

다른 프로젝트 설명도 이렇게 하면 내용을 줄일 수 있을 것 같습니다.

```
Role: Lead/Senior Server Programmer

Description: Senior architect responsible for designing and developing core features of back-end servers to support 3D Mobile MMORPG Kaiser. 


Responsibility: 
Used Agile methodology for design and development of project.
Developed backend servers to support game service.
```

* 간략히 변경 가능 내용  #3 
각 프로젝트의 Environment 은 skill set에 포함 될 수 있을 것 같습니다.

* Page break(페이지 나눔)
페이지 나눔이 적절하지 않은 곳이 보입니다.
워드 프로세서의 Page break 이 있습니다.  강제으로 페이지를 나누어 줍니다.
이 기능을 사용해 보시는 것이 어떨까요?

**Comment by qtsky89** [comment]
하신일이 많아 줄이기 힘드시겠지만, 중요한 것만 남기고 처낼것은 처내서 2 페이지 이내로 만드는게 중요할 것 같습니다.  페이지 넘김 사이사이에 이쁘게 보이도록 정리가 필요해 보입니다.
