### ISSUE TITLE
Logan's target companies

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#22]

**Comment by RoyMoon** [comment]
### Amazon
Website
http://www.amazon.com

### Industry
Internet Company

### size
10,001+ employees

### Headquarters
Seattle, WA

### Founded
1994

### Specialties
e-Commerce, Retail, Operations, and Internet

**Comment by RoyMoon** [comment]
### Google
Website
http://www.google.com

### Industry
Internet Company

### size
10,001+ employees

### Headquarters
Mountain View, CA

### Founded
1998

### Specialties
search, ads, mobile, android, online video, apps, machine learning, and virtual reality

**Comment by RoyMoon** [comment]
### Microsoft
### Industry
Computer Software
### Company size
10,001+ employees
### Headquarters
Redmond, WA
### Founded
1975
### Specialties
Business Software, Developer Tools, Home & Educational Software, Tablets, Search, Advertising, Servers, Windows Operating System, Windows Applications & Platforms, Smartphones,~ Cloud Computing, ~Quantum Computing, Future of Work, Productivity, AI, Artificial Intelligence, Machine Learning, Laptops, Mixed Reality, Virtual Reality, Gaming, Developers, and IT Professional

**Comment by RoyMoon** [comment]
### Ubisoft
### Industry
Video game industry

### Company size
10,001+ employees

### Headquarters
Montreuil,  France

### Founded
1986

### Specialties
Virtual Reality, Gaming

**Comment by RoyMoon** [comment]
### Electronic Arts
### Industry
Video game industry

### Company size
10,001+ employees

### Headquarters
Redwood City, California, U.S

### Founded
1982

### Specialties
Virtual Reality, Gaming
