### ISSUE TITLE
Juhwan's target companies

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#23]

**Comment by btakeya** [comment]
# Amazon Web Services (AWS)
## Website
* http://aws.amazon.com 
## Industry
* Information Technology and Services 
## Company size
* 10,001+ employees 
## Headquarters
* Seattle, WA 
## Founded
* 2006

**Comment by btakeya** [comment]
# Jigsaw (at Google)
## Website
* http://jigsaw.google.com 
## Industry
* Internet 
## Company size
* 51-200 employees
## Headquarter
* NY
## Founded
* 2011 
## Specialties
* Free Speech, Technology, Censorship, Google, Geopolitics, Alphabet, Internet, and Politics

**Comment by btakeya** [comment]
# Microsoft
## Industry
* Computer Software 
## Company size
* 10,001+ employees 
## Headquarters
* Redmond, WA 
## Founded
* 1975 
## Specialties
* ~Business Software, Developer Tools, Home & Educational Software, Tablets, Search, Advertising, Servers, Windows Operating System, Windows Applications & Platforms, Smartphones,~ Cloud Computing, ~Quantum Computing, Future of Work, Productivity, AI, Artificial Intelligence, Machine Learning, Laptops, Mixed Reality, Virtual Reality, Gaming, Developers, and IT Professional~
