### ISSUE TITLE
Gyumin's target companies

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#25]

**Comment by GyuminLee** [comment]
# FaceBook
## Website 
http://www.facebook.com 
## Industry 
Social media / network Company 
## size 
30,000 employees 
## Headquarters 
Menlo Park, California, U.S
## Founded 
February 4, 2004

**Comment by GyuminLee** [comment]
# Google
## Website 
http://www.google.com 
## Industry 
Internet Company 
## size 
98,771 employees 
## Headquarters 
Mountain View, California, U.S.
## Founded 
September 4, 1998

**Comment by GyuminLee** [comment]
# Amazon
## Website 
http://www.amazon.com 
## Industry 
Internet Company 
## size 
613,300 employees 
## Headquarters 
Seattle, Washington, U.S.
## Founded 
July 5, 1994

**Comment by GyuminLee** [comment]
# Trivago
## Website 
http://www.trivago.com 
## Industry 
Travel / Booking Company 
## size 
1,609 employees 
## Headquarters 
Düsseldorf, Germany
## Founded
January 2005
