### ISSUE TITLE
Benjamin's target companies

### ISSUE THREAD

**Issue by rygh4775** [rygh4775/interview-preparation#26]

**Comment by tgi01054** [comment]
# Amazon
## Website 
http://www.amazon.com 
## Industry 
Internet Company 
## size 
10,001+ employees 
## Headquarters 
Seattle, WA 
## Founded 
1994 
## Specialties 
e-Commerce, Retail, Operations, and Internet

**Comment by tgi01054** [comment]
# Google
## Website
http://www.google.com 
## Industry 
Internet Company 
## size 
10,001+ employees 
## Headquarters 
Mountain View, CA 
## Founded 
1998 
## Specialties 
search, ads, mobile, android, online video, apps, machine learning, and virtual reality

**Comment by tgi01054** [comment]
# Microsoft
## Industry
* Computer Software 
## Company size
* 10,001+ employees 
## Headquarters
* Redmond, WA 
## Founded
* 1975 
## Specialties
* Business Software, Developer Tools, Home & Educational Software, Tablets, Search, Advertising, Servers, Windows Operating System, Windows Applications & Platforms, Smartphones,~ Cloud Computing, ~Quantum Computing, Future of Work, Productivity, AI, Artificial Intelligence, Machine Learning, Laptops, Mixed Reality, Virtual Reality, Gaming, Developers, and IT Professional
